source:      .
destination: ./_site
exclude: ['*.less', 'node_modules']

url: http://www.dgbrt.fr

name: Webdesigner Freelance &agrave; Lille, int&eacute;grateur front-end, Dagobert Renouf
description: Design UI / UX et code front-end html5 / css3.
name_en: Freelance webdesigner and project manager, Dagobert Renouf DGBRT.
description_en: I lead webdesign projects to success with vision and skill. Web project management, webdesign and front-end development. I live in Lille, France.
permalink: none

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/404.html"